### ISSUE TITLE
Mariana Islands ATIS issue with one airport

### ISSUE THREAD

**Issue by dbnewell** [rkusa/DATIS#103]
Not able to get the ATIS station to work for Antonio B. Won Pat Intl. Below is the format I am currently using all other airport seem to work fine.

ATIS Antonio B. Won Pat Intl 118.60, TRAFFIC 340.20, VOICE WIN:David, NO QFE, NO HPA,

**Comment by rkusa** [comment]
Thanks for the report! Fixed in https://github.com/rkusa/DATIS/releases/tag/3.1.2 👍

**Comment by dbnewell** [comment]
Thank you!!
