### ISSUE TITLE
Pressure information without delimiter

### ISSUE THREAD

**Issue by mvee** [rkusa/DATIS#11]
Is it possible to express pressure information without spoken "decimal"? Multiplying with 100, so 29.92 would be 2992. I think it would be in line with real world expression.

**Comment by rkusa** [comment]
The Altimeter part of the report should already be without the decimal: https://github.com/rkusa/DATIS/blob/master/datis/src/station.rs#L89-L91
Are you maybe using an older version?

**Comment by rkusa** [comment]
Please reopen, if you still encounter this issue with the most recent version
