### ISSUE TITLE
Airport Names

### ISSUE THREAD

**Issue by Commiccannon** [rkusa/DATIS#125]
Can i please get a list of names that DATIS requires? Having trouble getting anderson afb working.
Thanks

**Comment by rkusa** [comment]
It should almost always be the exact name shown on the F10 map. So for Mariana you have:
```
Andersen AFB
Antonio B. Won Pat Intl
North West Field
Olf Orote
Pagan Airstrip
Rota Intl
Saipan Intl
Tinian Intl
```

In your case it might be the following typo, it's Anders`e`n AFB.
