### ISSUE TITLE
ATIS at Senaki

### ISSUE THREAD

**Issue by 132ndNeck** [rkusa/DATIS#13]
First, thanks for a great program!

I am unable to get ATIS to work for Senaki-Kolkhi for some reason. Do I need to add something specific for adding it to Senaki?

I have tried both naming it Senaki and Senaki-Kolkhi.

I have it working for Batumi, Vaziani, Kobuleti and Kutaisi (which is the only ones, in addition to Senaki that I have tried)

**Comment by rkusa** [comment]
`Senaki-Kolkhi` works for me (e.g. `ATIS Senaki-Kolkhi 254.000`). Which version are you using?

**Comment by rkusa** [comment]
If you cannot hear the report for Senaki, could you  check whether the report for Senaki-Kolkhi is still exported into `Logs\atis-reports.json`?

**Comment by 132ndNeck** [comment]
I am using latest version of DCS Open Beta.
Using DATIS: [0.8.0] - 2019-04-23.
Latest version of SRS.

I get the following from the log:

![bilde](https://user-images.githubusercontent.com/26002570/62358959-24a1c400-b516-11e9-95ed-6f20d3e8cd3f.png)


![bilde](https://user-images.githubusercontent.com/26002570/62358997-36836700-b516-11e9-87ff-5d36a23ed52f.png)


And verified in the Mission Editor that Senaki is set-up just like the other airfields.

**Comment by 132ndNeck** [comment]
I have attached the logs and the .miz in Issue #15 for more troubleshooting.

**Comment by rkusa** [comment]
Seems to be related to the specific mission file you are using 😕, see https://github.com/rkusa/DATIS/issues/15#issuecomment-520918651

**Comment by rkusa** [comment]
I am also closing this issue, again, feel free to re-open the issue if it still doesn't work for you
