### ISSUE TITLE
Possibility to read set SRS port from DCS-SRS-AutoConnectGameGUI.lua

### ISSUE THREAD

**Issue by mvee** [rkusa/DATIS#14]
Could this connection information as used in srs.rs
let mut stream = TcpStream::connect("127.0.0.1:5002")?;

be read from \Scripts\Hooks\DCS-SRS-AutoConnectGameGUI.lua

Line9: SRSAuto.SERVER_SRS_HOST = "hostname.url:port"

First just the :port if it's defined, otherwise just assume :5002

Would be great for multi-instance servers. Thanks!

**Comment by rkusa** [comment]
Good idea! I was initially planing to add the port as a setting to the DCS options GUI (where you also insert the gcloud key), but this approach might be more convenient 👍

**Comment by rkusa** [comment]
![Capture](https://user-images.githubusercontent.com/409021/62965420-4c8e0300-be05-11e9-823d-531597e4c622.PNG)

I decided to add a port setting, instead of dealing with extracting the port from a lua file

**Comment by mvee** [comment]
That's great! After a initial setup that's not a thing one would touch often so that works fine. Might be even better if SRS is run on a different address than DCS. Thanks!
