### ISSUE TITLE
Calling WinRT API failed with error code 2147942402

### ISSUE THREAD

**Issue by T-Bone1337** [rkusa/DATIS#145]
[DATIS.log](https://github.com/user-attachments/files/17758129/DATIS.log)

See log file, I get the error that a file was not found. I use Windows Server 2022, which dependencies do I need?

**Comment by rkusa** [comment]
Hm, sounds similar to the following, can you check the steps described in the response here: https://learn.microsoft.com/en-au/answers/questions/230849/windows-media-speechsynthesis-speechsynthesizer-co ?

**Comment by T-Bone1337** [comment]
> Hm, sounds similar to the following, can you check the steps described in the response here: https://learn.microsoft.com/en-au/answers/questions/230849/windows-media-speechsynthesis-speechsynthesizer-co ?

That was the solution and now DATIS works as it should. Thanks for the help, brilliant tool!  👍

**Comment by rkusa** [comment]
Glad it worked and good to hear that the tool still brings some value even though I haven't worked on it for quite a while
