### ISSUE TITLE
ATIS not broadcasting?

### ISSUE THREAD

**Issue by 132ndNeck** [rkusa/DATIS#15]
With reference to Issue #13 

I only get output from Kutaisi and Vaziani. When using the AWACS overlay from SRS, only 131.4 and 140.4 broadcasts any information.

![bilde](https://user-images.githubusercontent.com/26002570/62360996-5ddc3300-b51a-11e9-8f8f-92e05247985e.png)

This is the DATIS log:
![bilde](https://user-images.githubusercontent.com/26002570/62360271-b6aacc00-b518-11e9-86ce-df5417952a98.png)

I have the following information setup for the various stations:

ATIS Batumi 131.400, TRAFFIC 131.200, VOICE en-US-Standard-B
ATIS Kobuleti 133.400, TRAFFIC 133.200, VOICE en-US-Standard-E
ATIS  Senaki-Kolkhi 132.400, TRAFFIC 132.200, VOICE en-US-Standard-D
ATIS Kutaisi 134.400, TRAFFIC 134.200, VOICE en-US-Standard-E
ATIS Vaziani 140.400, TRAFFIC 140.200, VOICE en-US-Standard-A

**Example Batumi (BLUE airfield and blue unit):**
![bilde](https://user-images.githubusercontent.com/26002570/62359896-063cc800-b518-11e9-8458-ab8727faafd4.png)

**Example Kobuleti (RED Airfield and red unit):**
![bilde](https://user-images.githubusercontent.com/26002570/62360079-60d62400-b518-11e9-8e15-6ddc4d052020.png)

**Attachements (in the .zip file):**
- atis-reports.json
- DATIS.log
- The .miz I have used it on (132nd Virtual Wing standard training mission, TRM)

[DATIS Errors 132nd_TRM.zip](https://github.com/rkusa/DATIS/files/3460576/DATIS.Errors.132nd_TRM.zip)

**Comment by rkusa** [comment]
Found the issue ... It converts `"133.400"` into `133399992` 🤦‍♂  I'll try to find a fix. Also, I couldn't test your attached mission, due to all the mods necessary for it, but I copy and pasted

```
ATIS Batumi 131.400, TRAFFIC 131.200, VOICE en-US-Standard-B
ATIS Kobuleti 133.400, TRAFFIC 133.200, VOICE en-US-Standard-E
ATIS Senaki-Kolkhi 132.400, TRAFFIC 132.200, VOICE en-US-Standard-D
ATIS Kutaisi 134.400, TRAFFIC 134.200, VOICE en-US-Standard-E
ATIS Vaziani 140.400, TRAFFIC 140.200, VOICE en-US-Standard-A
```

into a new mission and I have at least all stations (including ` Senaki-Kolkhi`)

**Comment by rkusa** [comment]
It should work now. Since I cannot test your mission, due to me missing a lot of mods, I've attached a new mission that just contains ATIS stations with the same definition you are using:

```
ATIS Batumi 131.400, TRAFFIC 131.200, VOICE en-US-Standard-B
ATIS Kobuleti 133.400, TRAFFIC 133.200, VOICE en-US-Standard-E
ATIS Senaki-Kolkhi 132.400, TRAFFIC 132.200, VOICE en-US-Standard-D
ATIS Kutaisi 134.400, TRAFFIC 134.200, VOICE en-US-Standard-E
ATIS Vaziani 140.400, TRAFFIC 140.200, VOICE en-US-Standard-A
```

[issue-15.zip](https://github.com/rkusa/DATIS/files/3498052/issue-15.zip)

Could you confirm that all five stations in this mission work for you?

In case you are able to remove all the mod-dependencies from your mission, I am also willing to investigate why some stations in there are not working.

**Comment by rkusa** [comment]
I'll close this issue for now. Please feel free to re-open it, if you still have the issue
