### ISSUE TITLE
ATIS not updating with Dynamic weather

### ISSUE THREAD

**Issue by 132ndNeck** [rkusa/DATIS#16]
I have tried to let the server run with Dynamic weather.
It does not look like DATIS picks up changes in the weather for the subsequent ATIS messages.

**Comment by rkusa** [comment]
Theoretically, wind speed, wind direction, temperature and pressure should update for dynamic weather. However, I'll check whether it is not working anymore, thanks for the report 👍 (I also get back to you regarding the other issues this week)

**Comment by rkusa** [comment]
I've checked, and you are right, the report is not changing, but the script is reading the current data from DCS for each report. However, are we sure that the weather in DCS is changing?

What works though is, that with dynamic, stations at different positions, will have a different report.

**Comment by rkusa** [comment]
This was supposedly fixed back in version 1.0.0-alpha.3. I’ll thus close this for now.
