### ISSUE TITLE
Support for new SRS Network Change

### ISSUE THREAD

**Issue by ciribob** [rkusa/DATIS#19]
Hi!

As a heads up - there is a new SRS beta here: https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.7.0.0

The major change is the VoIP layer is now entirely UDP based as it used to be but otherwise there are no other changes to the packet layout itself

Each VoIP packet has a packet number - a 64 bit unsigned long that must be incremented for the Jitter buffer to work. It will overflow but in a long while... and when it does you'll only lose audio for 5 seconds or so while the buffer drains - and then back on it so not really a worry 👍 

I'm away for a week and going to try to get a few people to test this release and happy to wait until you're happy with it!

Thanks for your great work

**Comment by rkusa** [comment]
Thanks for the heads up! 👍 

I've upgraded DATIS to work with the network changes. I didn't encounter any issue yet, everything looks good so far - but I'll give it some additional testing the next couple of days.

If released [0.10.0-beta1](https://github.com/rkusa/DATIS/releases/tag/0.10.0-beta1) in case someone already wants to run SRS 1.7.0.0 in combination with DATIS.

**Comment by ciribob** [comment]
Looks good 👍

**Comment by ciribob** [comment]
Released version 1.7.0.2 - but it sets minimum network version to 1.7.0.0 so should be good 👍

**Comment by rkusa** [comment]
Thanks for the update 👍
