### ISSUE TITLE
Non Airfield ATIS

### ISSUE THREAD

**Issue by bunkerjunker** [rkusa/DATIS#21]
Is it currently possible to have a non airfield ATIS set up.  For example, we use a training range and would like to have weather info for the range available, but the closest air field is over 60 miles away.

Thanks

**Comment by rkusa** [comment]
Interesting use case. While you could use the static unit setup method for now, since this uses the static unit‘s position for the weather data, I‘ll think about an alternative setup method that does not tie a station to an airfield.

**Comment by rkusa** [comment]
Pure weather stations are added in https://github.com/rkusa/DATIS/releases/tag/1.1.0-rc.1
