### ISSUE TITLE
Support for Dedicated Server Client

### ISSUE THREAD

**Issue by Kocrachon** [rkusa/DATIS#26]
Currently, the dedicated server client does not have a "SPECIAL" menu or any sort of UI in order to put in the API key.

Perhaps setting up a key file or windows / system variable that the script reads from as an alternative in order to use DATIS with a dedicated server client?

**Comment by rkusa** [comment]
You can also edit `Saved Games\DCS.openbeta\Config\options.lua` directly. In there is a `plugins` section, where you can either add a `DATIS` key or edit it, if it already exists. Those are the options there:

```
options = {
	["plugins"] = {
		["DATIS"] = {
			["awsAccessKey"] = "",
			["awsPrivateKey"] = "",
			["awsRegion"] = "eu-central-1",
			["debugLoggingEnabled"] = true,
			["gcloudAccessKey"] = "",
			["srsPort"] = "5002",
		},
	},
}
```

Is this good enough as an alternative to start DCS with a GUI once for changing the settings?
