### ISSUE TITLE
Using TTS (no Google Cloud or Amazon Web Services)

### ISSUE THREAD

**Issue by AzzameenF18** [rkusa/DATIS#27]
Hello, I have not managed to make them operate through TTS, without using Google or Amazon services, could you briefly explain how to do it? Thank you

**Comment by rkusa** [comment]
- Install DATIS
- Add a static unit somewhere at your airfield in your mission and name as follows:

```
ATIS Kutaisi 251.000, TRAFFIC 252.000, VOICE WIN
```

(replace Kutaisi with the airfield you want to create an ATIS station for)

That should be it. If you did that and it does not work, could you enable the debug output (in the settings) and send me the logs?

**Comment by rkusa** [comment]
[ATIS WIN TTS example.zip](https://github.com/rkusa/DATIS/files/3854471/ATIS.WIN.TTS.example.zip)

Here is an example mission with an ATIS station for Kutaisi using Windows' TTS.

**Comment by AzzameenF18** [comment]
Ok, everything perfect I didn't read "VOICE WIN"  :-)

Thanks you!!!!
