### ISSUE TITLE
Issue to get it working after update

### ISSUE THREAD

**Issue by 132ndNeck** [rkusa/DATIS#28]
I have tried to update DATIS to latest version.
DATIS worked fine before we updated SRS to last release 1.7.X.X
Installed 1.0.0-alpha.5
(copied the files over in Mods and Scripts)

I get the following log, so something is happening:
[DATIS.log](https://github.com/rkusa/DATIS/files/3854419/DATIS.log)

**Comment by 132ndNeck** [comment]
When I tried to install verson 1.0.0-alpha.4 I got the following log:
[DATIS.log](https://github.com/rkusa/DATIS/files/3854439/DATIS.log)

So, now it created the Json files, but it is still not working

**Comment by rkusa** [comment]
Thanks for the report! I saw the same issue after upgrading to SRS 1.7.0.3, and it should be fixed now https://github.com/rkusa/DATIS/releases/tag/1.0.0-alpha.6
Does this version work for you as well?

**Comment by 132ndNeck** [comment]
I'll test now, I'll report back once tested

**Comment by 132ndNeck** [comment]
Working again!
Thanks alot :)

Great work with this program
