### ISSUE TITLE
Problems with Beta 6

### ISSUE THREAD

**Issue by AzzameenF18** [rkusa/DATIS#29]
Hello, I have set up a mission in the Caucasus with several ATIS frequencies as a static object (putting the name "ATIS [airport] [FREQ]"). The SRS server detects the clients, but tunes the frequency and nothing is heard. I have the Google Cloud key, and in other versions it worked, but not in this one. He also tried putting, VOICE WIN, but still not heard. I attached the log, but it doesn't give any problem. Any ideas?
[DATIS.log](https://github.com/rkusa/DATIS/files/3875896/DATIS.log)

**Comment by rkusa** [comment]
Hi @AzzameenF18 thanks for the report, could send me the logs again after enabling the Debug logging (in the DATIS settings inside DCS' SPECIAL options)? Thanks

**Comment by AzzameenF18** [comment]
Hi, the new datis.log (in this moment, the ATIS Stations is via static object, VOICE WIN.

[DATIS.log](https://github.com/rkusa/DATIS/files/3876746/DATIS.log)

**Comment by AzzameenF18** [comment]
Hello, sorry for the inconvenience, I think it is SRS failure, since it does not connect me against DCS (VOIP and server yes) So no matter how much I change the frequency it is impossible for me to receive anything. Greetings and sorry for the inconvenience
