### ISSUE TITLE
Windows TTS not working, still asking for Google key

### ISSUE THREAD

**Issue by rcflyinghokie** [rkusa/DATIS#30]
I am trying to use WIndows TTS in lieu of Amazon or Google but I am still getting the following error:

`2019-11-22T15:22:16.040312300-05:00 ERROR datis_core - Cannot start Khasab with TTS provider Google Cloud (Voice: StandardC) due to missing Google Cloud key`

I have selected VOICE WIN in my mission editor static objects and do not know why it is still trying to use Google.  Any help would be appreciated!  Thanks!

**Comment by rkusa** [comment]
Can you post the exact name you've used for your static object?

**Comment by rcflyinghokie** [comment]
I ended up using Google and its been working.
