### ISSUE TITLE
Using SRS crate as a standalone client

### ISSUE THREAD

**Issue by TheZoq2** [rkusa/DATIS#32]
Hi, with DCS now [working really well on linux](https://www.protondb.com/app/223750) I have a desire to also get SRS to work. Unfortunately, with SRS being a C# .net program, it seems to crash inside wine, and i'm not experienced enough with wine or C# to look into fixing that.

However, I stumbled across this project, and since it's written in rust I'm way more confident in modifying it to do what I want.

I thought I would start by trying to receive voice packets from a server and get them to play. I have succesfully connected to a server, but when I turn on `recv_voice` in the `client.start` function, the program exits saying "voice stream was closed unexpectedly" after the first iteration of sending pings.

Without `recv_voice`, everything seems to work fine (no crashes at least). Am I using something here incorrectly, or is the srs crate simply not set up to do what I want yet? For reference, I'm testing against a server at srs.thefraternitysim.com

The changes I've made compared to this project can be found here https://github.com/rkusa/DATIS/compare/master...TheZoq2:master

**Comment by rkusa** [comment]
Hey, wow that is quite an ambiguous project your are thinking about! I was thinking about hosting my DCS server on linux but stopped pursuing this thought, because I also couldn't get SRS (server) working via wine - so I can totally understand your motivation!

To your issue. The whole receiving part of this project is in an really early state and currently only used in a local speech recognition prototype. So it is unfortunately not bullet proof, yet. Anyway, I think I found the issue you've encountered and fixed it in the commit linked above. Does it work for you now?

**Comment by TheZoq2** [comment]
Thanks for the quick reply and fix.

> Hey, wow that is quite an ambitious project your are thinking about!

Hopefully not too ambitious, we'll see how far I get :)

> To your issue. The whole receiving part of this project is in an really early state and currently only used in a local speech recognition prototype. So it is unfortunately not bullet proof, yet

That was my assumption, i'll let you know if I find any other issues, hopefully i'll also be able to fix those and contribute back :)

Anyway, I think I found the issue you've encountered and fixed it in the commit linked above. Does it work for you now?

Yep, seems to have done the trick! I'm now receiving packets, so I guess I'll have to start thinking about how to play the audio. What format is the audio data in, is it raw audio, or compressed/encoded somehow?

**Comment by rkusa** [comment]
> What format is the audio data in, is it raw audio, or compressed/encoded somehow?

It is OPUS encoded. You could use `audiopus` to decode it:

```rs
use audiopus::{coder::Decoder, Channels, SampleRate};

let mut dec = Decoder::new(SampleRate::Hz16000, Channels::Mono)?;

// for each packet
let mut output = [0i16; 256];
let len = dec.decode(input, &mut output[..], false)?;
```

The above snippet is missing things like handling lost packets though. and the opus decoder is sometimes a bit picky about the data it receives.

**Comment by TheZoq2** [comment]
Thanks for the help! That was a lot easier than I thought it would be, I now have audio received SRS playing through rodio. As you said, lost packet stuff needs to be dealt with, but just ignoring them works well enough for now.

The only change to the `srs` crate I've made is to change the listen addres on the UDP socket from `127.0.0.1` to `0.0.0.0`. Do you want me to make that configurable in a PR so I can just depend on that crate without modifications?

**Comment by rkusa** [comment]
> Thanks for the help! That was a lot easier than I thought it would be, I now have audio received SRS playing through rodio. As you said, lost packet stuff needs to be dealt with, but just ignoring them works well enough for now.

Awesome!

> The only change to the `srs` crate I've made is to change the listen addres on the UDP socket from `127.0.0.1` to `0.0.0.0`. Do you want me to make that configurable in a PR so I can just depend on that crate without modifications?

Sounds good, I happily such a PR
