### ISSUE TITLE
Feature request: Manual text in message

### ISSUE THREAD

**Issue by 132ndNeck** [rkusa/DATIS#35]
I have a feature request.
Would it be possible to setup a completely manual message? Not using the ATIS format.
I know this may be out of the scope for DATIS, but want to check the possibilites.

The reason for my request, is that I want to introduce the element of jamming of frequencies. So if the mission host could use manual message, he could simply add in a text for the actual jamming.
The idea is to make activity in the frequency, so flights intending to use the frequency need to switch to a secondary frequency. (Or jamming AWACS /JTAC primary frequencies).

With DATIS you already have the LOS function (or atleast I think you do?). As the idea is to have the jammer tied to a specific unit/location in the .miz, so it only effect people that in LOS to that location.

**Comment by rkusa** [comment]
Interesting use-case 👍

There is already https://github.com/rkusa/DATIS/tree/master/crates/radio-station which might even be a better fit for your use-case? So instead of providing text, you provide an audio file which could either contain noise or recordings from actual busy flight frequencies. However, the in-game position of such a "radio station" cannot be configured yet, it is [hard-coded for now](https://github.com/rkusa/DATIS/blob/master/crates/radio-station/src/main.rs#L56). I am planning to tie it to a static unit, like it is [possible for ATIS stations](https://github.com/rkusa/DATIS#using-static-units) eventually though.

> With DATIS you already have the LOS function (or atleast I think you do?)

Yes, this works already

**Comment by 132ndNeck** [comment]
> There is already https://github.com/rkusa/DATIS/tree/master/crates/radio-station which might even be a better fit for your use-case? So instead of providing text, you provide an audio file which could either contain noise or recordings from actual busy flight frequencies. However, the in-game position of such a "radio station" cannot be configured yet, it is [hard-coded for now](https://github.com/rkusa/DATIS/blob/master/crates/radio-station/src/main.rs#L56). I am planning to tie it to a static unit, like it is [possible for ATIS stations](https://github.com/rkusa/DATIS#using-static-units) eventually though.

Excellent, I have not tried that yet. Will do a test this weekend. If it had the same functionality like ATIS stations where it is tied to a static unit it would be great.

On that, would it be possible to tie it to a normal group, and not a static unit? The rationale for this is to use triggers and late activate the unit at a certain time, to be able to decide when the jamming takes place. Not sure if that is possible or feasible at all, but worthing suggesting it.

**Comment by rkusa** [comment]
> Excellent, I have not tried that yet. Will do a test this weekend (but looking at the link you provided it is not very clear to me how to use it. I am not a developer or too experienced with tech stuff). If it had the same functionality like ATIS stations where it is tied to a static unit it would be great.

That is true, it currently can only be used from command-line which is definitely not user-friendly. I was planning to wire it up to units/statics in the mission similar to the way it is done for the ATIS stations. However, I don't know when I'll find the time to get to it.

> The rationale for this is to use triggers and late activate the unit at a certain time, to be able to decide when the jamming takes place. Not sure if that is possible or feasible at all, but worthing suggesting it.

Interesting point, thanks for bringing this up. At least the way the ATIS stations are extracted from static units, does not care about whether the group/static is active or alive. But I agree that this might be something useful to have.

**Comment by rkusa** [comment]
> On that, would it be possible to tie it to a normal group, and not a static unit? The rationale for this is to use triggers and late activate the unit at a certain time, to be able to decide when the jamming takes place. Not sure if that is possible or feasible at all, but worthing suggesting it.

Out of curiosity, what benefits do you see from using DATIS for that use-case and not a DCS trigger that broadcasts a sound file through a certain frequency? While this audio wouldn't go through SRS, it would still block a proper usage of the frequency I guess?

**Comment by 132ndNeck** [comment]
Sorry for the late answer.
Benefit is that it uses the LOS and SRS.  But I have not tested it to see the effect if it would block a frequency properly, so maybe that is a solution. I will test.

**Comment by 132ndNeck** [comment]
Bumping this, as I have edited my answer above, and you may not have seen it.
(And I understand very well, that this is low on the priority :)  )

**Comment by rkusa** [comment]
Initial implementation of that feature is now available (requires at least the current SRS 1.8 beta):
https://github.com/rkusa/DATIS/releases/tag/1.0.0-alpha.10

I'll add some documentation and debug logging later. See the [Changelog](https://github.com/rkusa/DATIS/blob/master/CHANGELOG.md#100-alpha10---2020-05-01) for information of how to set it up. Example: `BROADCAST 260, VOICE AWS:Brian: HELP HELP`
