### ISSUE TITLE
Choose random information letter at the start

### ISSUE THREAD

**Issue by obfuscoder** [rkusa/DATIS#38]
It would be great if the information letter at mission start would be random. We usually start the mission/server shortly before we do the flying and everyone knows already that it is going to be information letter A.

**Comment by Lugghawk** [comment]
Seems reasonable. I wanted to know the specifics of this and whether it was okay to have different stations on different information letters, it seems like the stations are not related at all IRL. According to wikipedia (https://en.wikipedia.org/wiki/Automatic_terminal_information_service):

>  It is given a letter designation (e.g. bravo) from the ICAO spelling alphabet. The letter progresses through the alphabet with every update and starts at alpha after a break in service of 12 hours or more.

So I think we're okay if we just pick an offset between 0-25 when DATIS starts up, and adding that to the index of the phonetic alphabet we're looking up. There's no modeling of the "starts at alpha after a break in service of 12 hours or more" in DATIS, and I don't think there needs to be.

I'll see if I can give this a go sometime soon.
