### ISSUE TITLE
Incorrect wind speed

### ISSUE THREAD

**Issue by LazyBoot** [rkusa/DATIS#40]
DCS Briefing:
![DCS Briefing](https://cdn.discordapp.com/attachments/420225846196961280/683120741696536596/unknown.png)

LotAtc Weather Tab:
![LotAtcWeatherTab](https://user-images.githubusercontent.com/3827482/75598250-9a651280-5a9a-11ea-87bb-afc39492361a.png)

What DATIS said:
https://cdn.discordapp.com/attachments/492808167990886410/683122754534375548/DATIS.mp3

TL;DR:
Datis reported 5 knots, when DCS claims 5 m/s and lotatc 10 knots.

**Comment by LazyBoot** [comment]
Also as a sidenote... what's with all the decimals on the QFE?

**Comment by rkusa** [comment]
Thanks for the report! 👍
I recently changed the source of the wind speed and apparently now receive it as m/s and not in knots, I've thus re-added the conversion to knots.

> Also as a sidenote... what's with all the decimals on the QFE?

Those are actually not decimal places, but a hard to understand "or" that reports both `inHg` and `hPA`: `QFE 2995 or 1014`. It might be worth checking if this is better to understand with `WaveNet` (or Polly) voices and if not we could think about adding longer speaking pauses between those numbers.
