### ISSUE TITLE
Feature Request - Micraosft Azure Cognitive Services

### ISSUE THREAD

**Issue by Maverick87Shaka** [rkusa/DATIS#41]
I know that you have already included two of the mayor cloud provider ( Google/AWS), and due to  Home and Alexa probably they are really a step forward,  but maybe you can consider to add also Microsoft Azure Cloud and its cognitive services as well? Thanks.

https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/

**Comment by rkusa** [comment]
While I'll probably don't find the time to add it myself in the immediate near future, it is still a valid feature request and it is still possible that I'll do it just for fun eventually. Anyway, I'll add some labels to it to make the issue more visible to others that might be interested in hacking on DATIS. Thanks for the feature request

**Comment by ugene143** [comment]
As a total rust newbie, I gave this one a go. I copy-pasted most of the code from ths aws/glcoud-tts implementations and adapted it for azure cognitive services. Some(read most) of the parts are probably ugly and unnecessary.
I was able to obtain the bearer key but I always receive a "400 Bad Request" when executing the actual SSML request.
I have no idea what I am missing here. 
https://github.com/ugene143/DATIS/tree/feature/azure

**Comment by rkusa** [comment]
@ugene143 thanks for giving the implementation a try! I'll give it a look, maybe I can spot the issue

**Comment by rkusa** [comment]
@ugene143 I finally found the time to look into it. It looks like the Azure API requires a `User-Agent`. Adding `.header("User-Agent", "DATIS")` to the request fixed it

**Comment by Maverick87Shaka** [comment]
> 
> 
> @ugene143 I finally found the time to look into it. [It looks like](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#request-headers-1) the Azure API requires a `User-Agent` header. Adding `.header("User-Agent", "DATIS")` to the request fixed it

It's now part of the main branch or I've to use the @ugene143 one to test the Azure functionality?

**Comment by rkusa** [comment]
> It's now part of the main branch or I've to use the @ugene143 one to test the Azure functionality?

It is not part of `rkusa/DATIS`, yet

**Comment by ugene143** [comment]
I added the missing header field in this branch https://github.com/ugene143/DATIS/tree/feature/azure
Unfortunatly I am not able to test the it, because the build always fails (unresolved imports `winrt::Error ...)

**Comment by rkusa** [comment]
Implemented by @ugene143 in https://github.com/rkusa/DATIS/pull/90 and released as https://github.com/rkusa/DATIS/releases/tag/3.0.0-beta.3
