### ISSUE TITLE
Upcoming SRS compatibility 

### ISSUE THREAD

**Issue by LazyBoot** [rkusa/DATIS#43]
looks like the datis might not be compatible with the upcoming SRS version

https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.8.0.0

**Comment by rkusa** [comment]
I've released [a new version](https://github.com/rkusa/DATIS/releases/tag/1.0.0-alpha.9) that is upgraded to the protocol changes of SRS 1.8 👍
