### ISSUE TITLE
Duplicate ATIS and problem to transmit between players

### ISSUE THREAD

**Issue by mvee** [rkusa/DATIS#47]
![image](https://user-images.githubusercontent.com/17532699/81980297-ffaab780-9636-11ea-941e-3b48abbfeefe.png)

When a mission is loaded from mission triggers and the next mission is same/slightly altered version (time & weather conditions) that has all the same ATIS that are bound to static units. I think this started after SRS 1.8.x

Is there a timeout when mission end is detected so it would initialize stations again. It could be related to the mission too.

**Comment by rkusa** [comment]
The duplicates in the list might be just a UI issue of SRS. I've noticed the same and while looking into it, I also saw it for player clients. They often stay in the list even though they've disconnected. Do you hear the old ones still transmitting?

> problem to transmit between players
What issue do you have with transmitting between players?

**Comment by mvee** [comment]
Some do hear ATIS, some don't and those who don't cant event transmit to other players. Or so I've been told. Havent been affected it by myself yet.

**Comment by rkusa** [comment]
This will be fixed in the next SRS version

**Comment by rkusa** [comment]
Here we go, should be fixed with https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.8.0.4

**Comment by tukool4u** [comment]
> Hi, thanks for the report! The duplicates in the list might be just an UI issue of SRS. I've noticed the same and while looking into it, I also saw it for player clients. They often stay in the list even though they've disconnected. Do you hear the old ones still transmitting?
> 
> > problem to transmit between players
> 
> What issue do you have with transmitting between players?

Hi @rkusa, have you seen this problem (duplicating) anymore? I have two servers running and I get duplicate ATIS connections on both. Is there any issue with running two DCS servers through a single SRS server?

**Comment by rkusa** [comment]
@tukool4u I haven't observed it recently, but I wasn't actively looking for it either. Are they still just duplicates in the client list, or does it also have some functional impacts (like are you hearing them twice)?

**Comment by tobeyun** [comment]
> @tukool4u I haven't observed it recently, but I wasn't actively looking for it either. Are they still just duplicates in the client list, or does it also have some functional impacts (like are you hearing them twice)?

It is playing twice, but I think I found the problem. I have multiple DCS server instances running and a single SRS server instance. What I believe is happening is DATIS is broadcasting twice because I had two servers with DATIS tags and a single (shared) SRS server. Once I shut one of the servers down, it stopped. I didn't even think about it running from the missions of each. I just need to be mindful of ATIS frequencies between servers.
