### ISSUE TITLE
Feature Request - Fm on Radio.

### ISSUE THREAD

**Issue by robgrahamau** [rkusa/DATIS#51]
I've noticed that even if you set things to the lower freq's that are for fm ie 69000000 because there is no way to change the flag from Amplitude Modulation to Frequency Modulation you can't get the channels up on fm.

it would really be useful on the radio code especially.

**Comment by robgrahamau** [comment]
Added for radio crate still need to add for module:
https://github.com/robgrahamau/DATIS/commit/17d3b5a644bb8dd9c3564cd727e8982c5f22f361

**Comment by rkusa** [comment]
Thanks for the suggestion 👍
I am wondering if it's good enough to automatically derive the modulation from the frequency. E.g. make everything below or equal to `87.995` use FM, and use AM for all the other frequencies (ignoring that there are other ranges where both AM and FM are available)?

**Comment by robgrahamau** [comment]
how ever you want to do it it would make sense dcs only uses FM for the lower freq's as you said and not the higher, I forked your repo and added modulation selection to the command line radio etc, just used a -f but yeah in a lot of cases just auto selecting would make more sense.

**Comment by rkusa** [comment]
I have added an automatic modulation selection for now. I'll postpone a new release though to try to include a fix for #53 in the next release.
