### ISSUE TITLE
DATIS Not Authorized Error

### ISSUE THREAD

**Issue by jkegaly** [rkusa/DATIS#53]
Since upgrading to SRS 1.9.0.1 and subsequently DATIS to 2.0, DCS will no longer load DATIS.

Everything was working well on both products last versions...

Below is data from my dcs.log file

WARNING DCS: Not Authorized, no registry path: ./Mods/tech/DATIS
2020-06-29 15:04:39.474 INFO    Scripting: plugin: SKIPPED 'DATIS': not authorized

**Comment by neonbasschild** [comment]
same thing on my machine. I am guessing SRS 1.9.0.1 killed it.

**Comment by rkusa** [comment]
Thanks for the report @jkegaly, and thanks for confirming it @neonbasschild. Unfortunately, I cannot reproduce it on either my local installation nor on my server. However, it might be a similar issue to why e.g. SRS and LotATC had to move their mod from `DCS.openbeta\Mods\tech\` to `DCS.openbeta\Mods\services\`.

Could one of you try the following and see if that fixes the problem:
-  Move the DATIS mod from `Saved Games\DCS.openbeta\Mods\tech\DATIS` to `Saved Games\DCS.openbeta\Mods\services\DATIS`
- Replace `tech` with `services` in the first line of `DCS.openbeta\Scripts\Hooks\datis-hook.lua`:

    ```diff
    -package.cpath = package.cpath..";"..lfs.writedir().."Mods\\tech\\DATIS\\bin\\?.dll;"
    +package.cpath = package.cpath..";"..lfs.writedir().."Mods\\services\\DATIS\\bin\\?.dll;"
    ```

Please let me know if you don't feel comfortable doing such changes, I could also upload a test version that includes that change in this case.

Thanks 👍

**Comment by jkegaly** [comment]
Ah Ha! @rkusa That seems to have fixed it for me! Amazing such a small change could fix that error I was receiving.

2020-06-30 16:01:28.631 INFO    [DATIS]: Loaded
2020-06-30 16:01:44.576 INFO    [DATIS]: Started

🥇 😄 ✈️

**Comment by rkusa** [comment]
@jkegaly Thanks a lot for testing! I'll have to prepare a new release with that change then
