### ISSUE TITLE
Failed to retrieve unit position

### ISSUE THREAD

**Issue by NC-Cyborg** [rkusa/DATIS#54]
I was able to get DATIS to work with the Win TTS.  Great work by the way.

I am using SRS v1.9.0.1 and DATIS v2.0.0

I am having issues with the script from retrieving the carriers position.  Below is an excerpt from the DATIS log.

_**2020-07-01T04:49:33.036562700-04:00 ERROR datis_core - ATIS Big Stick failed: failed to retrieve unit position

Caused by:
    missing field `x`
2020-07-01T04:49:33.036562700-04:00 INFO datis_core - Restarting ATIS Big Stick in 60 seconds ...**_

On another note, how do you change the voice using Win TTS?

I have tried "Microsoft Zira" and just "Zira" but neither seem to work.  In the DATIS log I get (Voice: "Default"))

Thanks gents for putting this together!
[DATIS.log](https://github.com/rkusa/DATIS/files/4858173/DATIS.log)

**Comment by rkusa** [comment]
Hi, thanks for the report! Could you enable the Debug setting in the DATIS options and send me the Logs again? Or send me the mission (feel free to reduce the mission to the carrier)?
Try `WIN:Zira` for the voice.

**Comment by NC-Cyborg** [comment]
Thanks for getting back to me.  I set the code in options Db.lua  

debugLoggingEnabled = DbOption.new():setValue(true):checkbox()

DATIS log does not look any different.  But attached is the log and .miz file.

Thanks again.

[DATIS.log](https://github.com/rkusa/DATIS/files/4876541/DATIS.log)
[Unit Position.ZIP](https://github.com/rkusa/DATIS/files/4876542/Unit.Position.ZIP)

**Comment by rkusa** [comment]
I've added a screenshot to the Readme to show the settings where you could toggle the debug option. https://github.com/rkusa/DATIS/blob/master/docs/settings.jpg
If you don't want to start DCS with GUI, you could also update `DCS.openbeta\Config\options.lua`:

```diff
         ["DATIS"] = 
         {
             ["awsRegion"] = "eu-central-1",
             ["defaultVoice"] = "WIN",
-            ["debugLoggingEnabled"] = false,
+            ["debugLoggingEnabled"] = true,
```

But not really necessary anymore, since you've provided the mission - thanks for that! However, I don't have a solution yet since all stations work perfectly fine when trying the mission on my server. 🤔

I don't think that it is related to changes I've made for `2.1.0`, but would you still mind to check if you also have the error with [`2.1.0`](https://github.com/rkusa/DATIS/releases/tag/2.1.0)?

**Comment by NC-Cyborg** [comment]
I could never figure out how to get the GUI to work on the DCS server install.  I didn't think there was one.  But I am able to use the Web Base GUI for most of the missions that i run.  The DATIS code above is not in my options.lua file.  I thought about adding it but not sure where.  

But how would I enable the debugging for the DATIS log with the optionsData.lua or optionsDb.lua files downloaded?

I updated to 2.1.0.  I left it running over night and checked.  I am still getting the error.  But I logged into the server and was able to still listen to the ATIS  report.

_2020-07-08T22:20:07.575326800-04:00 ERROR datis_core - ATIS Big Stick failed: failed to retrieve unit position

Caused by:
    missing field `x`
2020-07-08T22:20:07.575326800-04:00 INFO datis_core - Restarting ATIS Big Stick in 60 seconds ..._

Attached is the log, but I was not able to enable debugging.  Sorry.

As for the voices, still no joy.  I am using the line below in the Situation window in the mission editor
ATIS Al Dhafra AB 258.200, TRAFFIC 251.000, VOICE WIN:Zira

Thanks again for working with me.

**Comment by rkusa** [comment]
> I left it running over night and checked. I am still getting the error. But I logged into the server and was able to still listen to the ATIS report.

Hmm, I'd guess there is something in the mission that messes with the carrier after a while. So either the carrier gets killed, or maybe the carrier script is respawning it with an new name - but I don't know how the carrier script in your mission works, so this is just a wild guess.

**Comment by rkusa** [comment]
I am quite positive that this has been fixed a while ago with https://github.com/rkusa/DATIS/commit/d39d06de40ee1931f847e1012bde6d2a70d45c45. The cause was that the carrier position numbers had an exponential format once in a while (e.g. `1.23e+10`) which my number format parser did not expect.
