### ISSUE TITLE
DATIS Stations fail with "An async operation failed"

### ISSUE THREAD

**Issue by stab-virtual-jabog32** [rkusa/DATIS#55]
Datis is currently not working for us.
We are running DCS 2.5.6.49798 with SRS 1.9.0.1 and DATIS 2.0.0.

See attached log file for detailed error messages
[DATIS.log](https://github.com/rkusa/DATIS/files/4869383/DATIS.log)

**Comment by rkusa** [comment]
Thanks for the report and logs. It's quite sad that Windows TTS only reports unhelpful error codes like `2147942402` ... so the only thing I know for sure is the Windows TTS is apparently not working on your Windows server. Which version of Windows is your DCS server running on? In the meantime, I'll also look into whether it is possible to get more meaningful errors out of Windows TTS ... The only temporary "workaround" for you might be to use GCloud or AWS TTS for now

**Comment by obfuscoder** [comment]
I can have a look into this. After all, I provided most of the code and are member of the vJabog32 ;-)

**Comment by rkusa** [comment]
> I can have a look into this. After all, I provided most of the code and are member of the vJabog32 ;-)

Headsup, I've switched from the C# program that got called from Rust, you've previously contributed to, to a pure Rust implementation via https://github.com/microsoft/winrt-rs recently (so I am basically calling WinRT bindings from Rust) - and the not so good error message comes from winrt-rs

**Comment by obfuscoder** [comment]
Uh ok ... then I cannot be of much help there. Too little time to learn Rust atm ;-)

**Comment by stab-virtual-jabog32** [comment]
Issue now solved for us.
Looks like the English (US) TTS pack has to be installed.
What keeps me wondering why it worked before. Maybe Windows 2004 update changed the behavior.
