### ISSUE TITLE
Wrong language.

### ISSUE THREAD

**Issue by Dampenstein** [rkusa/DATIS#58]
Hey! Just added this to our Persistant server and the voice is on swedish... How do i change this?

also I would love the get the information in text format aswell as in voice.

- Dampe

**Comment by Dampenstein** [comment]
I managed to fix the language but how to make it come up in text format?

**Comment by rkusa** [comment]
> I managed to fix the language but how to make it come up in text format?

How did you fix the voice - installing an English voice pack for Windows TTS?

DATIS does not have a in-game text output I am afraid. While a text only version is exported to `Saved Games\DCS\Logs\atis-reports.json`, it is probably not what you were asking for.

**Comment by Dampenstein** [comment]
Yeah i changed the TTS in windows to english.

I want this https://www.youtube.com/watch?v=MdH9FmbNabo&feature=youtu.be

but i guess that only possible with moose scripts?

I created a comms tower in the mission on Senaki. Named it Senaki-kolkhi. Is that the right name for it?

**Comment by rkusa** [comment]
> but i guess that only possible with moose scripts?

Yes

> I created a comms tower in the mission on Senaki. Named it Senaki-kolkhi. Is that the right name for it?

The name should be at least `ATIS Senaki-Kolkhi 251` (assuming you want the station to broadcast at freq 251).

**Comment by Dampenstein** [comment]
Alright thanks!
