### ISSUE TITLE
need some documentation for dedicated servers

### ISSUE THREAD

**Issue by derbuur** [rkusa/DATIS#59]
Hi, very nice project.
But it will be helpful if there are some explanations for setup a dedicated server without a view to the options settings.
Finally manged it by editing the optionsDB.lua, but it was hard to find the information in the net.
A example for setting up with AWS or GC will be helpfull.

best regards

**Comment by rkusa** [comment]
You are right, I'll add it to the README 👍

**Comment by mistermookiefun** [comment]
Could be nice because I can't get it to work on my dedicated server

**Comment by rkusa** [comment]
I've added a note about the `options.lua` file to the end of the [installation section](https://github.com/rkusa/DATIS#installation).
