### ISSUE TITLE
DATIS seems to ignore static objects if owning coalition is neutral

### ISSUE THREAD

**Issue by hawaiianryan808** [rkusa/DATIS#65]
DCS has introduced neutral coalition members.

If I create a static object named, e.g. ATIS Sochi-Adler 129.370, TRAFFIC 127.0, VOICE WIN:David and set it to a country in the neutral coalition then DATIS doesn't process this as an ATIS station.

Owning faction must be blue or red.

**Comment by rkusa** [comment]
Fixed and released as `2.2.0-beta.3`, thanks for the report!
