### ISSUE TITLE
Evaluate Reddit feedback

### ISSUE THREAD

**Issue by rkusa** [rkusa/DATIS#7]
https://www.reddit.com/r/hoggit/comments/9tmc4s/new_feature_gaw_now_has_atis/e8xl7sp/
https://www.reddit.com/r/hoggit/comments/9tmc4s/new_feature_gaw_now_has_atis/e8xsn4w/

- [X] order in Discord by StratJeff: Station, ATIS, Time, Winds, Vis, Clouds, Temp/DP, altimeter, then remarks

**Comment by Lugghawk** [comment]
> After I hear the 2-digit temperature in Celsius, I then expect to hear the dew point in Celsius. I don't think there's anything equivalent in DCS for the time being, but I think a good placeholder would be to just subtract 5 or 10 degrees or something (unless it's raining). Or maybe pull it from the real world data you're using.

Seems reasonable. We'd need to use the 5-10 degree suggestion, but I'm not sure if it has any effect for the users of GAW.

>The altimeter doesn't usually have the decimal in it (at least I've never heard it). You just hear "two niner niner two" and the decimal is implied.

This is probably worth doing.

>I expect to hear the zulu time after I hear the ATIS designator.

Also probably worth doing.

>Don't say "oh." Say "Zero" (ZEE-RO).

Worth doing.

>I couldn't quite make out what was said after the visibility. That's where you're supposed to denote the cloud conditions. Was it "Few 160"?. I think it should say "cloud conditions" before it says that.

Worth doing.

>There needs to be a larger gap between each section. The visibility number and what I think was the cloud conditions just kinda ran into each other.

Flathand. The example given would be solved with the cloud conditions part, but I think adding gaps wouldn't hurt.

**Comment by rkusa** [comment]
> After I hear the 2-digit temperature in Celsius, I then expect to hear the dew point in Celsius. I don't think there's anything equivalent in DCS for the time being, but I think a good placeholder would be to just subtract 5 or 10 degrees or something (unless it's raining). Or maybe pull it from the real world data you're using.

I am not sure if we should start adding placeholders for data that is not supported in DCS. I don't have a strong opinion here, but would lean towards not adding placeholders.

---

From https://www.reddit.com/r/hoggit/comments/9tmc4s/new_feature_gaw_now_has_atis/e8xydxi/

>  temperature 24, dew point 6 ( it’s always in Celsius so you don’t state it)

I am inclined to keep the celcius. I agree that we should aim at being realistic, but I still would prefer it being as accessible for new people (in terms of not being familiar with ATIS) as possible.

**Comment by rkusa** [comment]
https://www.reddit.com/r/hoggit/comments/9tmc4s/new_feature_gaw_now_has_atis/e8zpjmb/

> Perhaps it's different in other areas, but I've never heard "cloud conditions". I've only ever heard "sky condition", and I believe that's the proper way to say it, as they'll also add on non-cloud weather at this point, such as mist or rain.

> A simple way to get the dew point would be to use the cloud layer altitude. Standard temperature lapse rate is about 2 degrees Celsius for every 1000 ft. So however high above the surface the clouds are, take that number of thousand, and multiply it by two. The number you get is the temperature dew point spread. Subtract that from your surface temperature, and that's about your dew point. For example, say I wanted the dew point at Batumi, which is just about sea level. If the temperature is 25 degrees Celsius, and the clouds are at 6000 feet, then then the spread would be 12 degrees. 12 degrees from 25 would be 13 degrees Celsius, which is about what the dew point ought to be.

**Comment by rkusa** [comment]
> just called my local airport's AWOS and the delay between each play is about 12-14 seconds.

https://github.com/rkusa/DATIS/blob/master/datis/src/srs.rs#L236-L238

**Comment by rkusa** [comment]
If anyone is interested in discussion some of those points or other ones, feel free to open a separate issue for that
