### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alrip74** [rkusa/DATIS#72]
Hello! 
I tried to install your wonderful mod. I put mod and script files in saved games dcs open Bêta server to make it avalaible for my server team. I modified options.lua like in your readme. 
Nothing happened when I tried your test mission. I don’t have any log file... where is the problem ?

**Comment by alrip74** [comment]
Thanks a lot !

**Comment by rkusa** [comment]
Hi, can you search the `Logs/dcs.log` file after you've started a mission for lines that contain "DATIS" - are there any entries?

**Comment by alrip74** [comment]
Hi! I’ve just found the solution. I download an other package ( prebuilt) and it works fine thanks a lot

**Comment by rkusa** [comment]
Awesome 👍
