### ISSUE TITLE
Slow distorted ATIS broadcast Windows server 2016

### ISSUE THREAD

**Issue by dbnewell** [rkusa/DATIS#79]
Hello I recently implemented you DAITS on our DCS squadron servers. When the ATIS broadcast is played back via the assigned SRS freq the speech is very slow. This is running on a windows 2016 server machine. The default windows tts voices are David Mobile, Mark Mobile and Zira Mobile. Any help resolving this would be much appreciated!

**Comment by dbnewell** [comment]
found an issue with the tts setting in windows 2016 server

**Comment by rkusa** [comment]
I am glad you already found the issue! Do you remember which setting you've changed, in case anyone else encounters the same issue in the future?

**Comment by dbnewell** [comment]
Yes, for some reason I had to go to speech in the windows settings and adjust the speed slider up from the default 10 to 12 and that completely cured it on the windows server 2016 machine. On a standard windows 10 machine the defaults in tts worked fine.

Sent from Mail for Windows 10

**Comment by dbnewell** [comment]
Markus,

	As I stated in the issues, I launched this on our squadron servers and it has drawn great reviews from our pilots! We typically fly large operations with live ATC and for example flying out of Nellis we extracted the weather data from the automated ATIS pull and wrote a custom broadcast as seen below. Just curious if there might be future expanded capability to add to more information to the automatic ATIS pulls where we could create something similar to what is below and not wreck the automated weather pulls from the game and the updating information letter? Oh, and possibly add the in game time in Zulu? Thank you for your efforts on this it is greatly appreciated by the community!!

BROADCAST 270.1, VOICE WIN:David: Nellis Air Force Base information Whiskey,  Runway in use zero three,  Wend zero four three at three knots,  Visibility one zero,  Ceiling ten thousand broken,  Temperature one four degrees celcius,  Altimeter, two niner niner two,  Ground on three two seven decimal zero megahertz,  Departure on two six zero decimal zero megahertz,  REMARKS QFE two eight zero zero or niner four eight,   Advise on initial contact you have info[rmation Whiskey  


Sincerely
Doug

Sent from Mail for Windows 10

**Comment by rkusa** [comment]
Thanks for the information on how you were able to fix it 👍

I might be missing something but it looks like most of the infos in your example are already part of the automated ATIS, except for slightly different wording here and there. Am I missing something?

The next version will allow you to customise the active runway https://github.com/rkusa/DATIS/pull/76 and information letter that the automated ATIS starts with https://github.com/rkusa/DATIS/pull/69.
