### ISSUE TITLE
QFE Readout timing

### ISSUE THREAD

**Issue by FernandoNotedigo** [rkusa/DATIS#83]
Hi Everyone!
I suggest more delay between the 2 numbers and the OR word during QFE Phrasing (QFE XXXX or YYY).
The last digit from XXXX, the "OR" and the first digit from YYY are heavily mixed, specially for non english people.

Thanks!

**Comment by rkusa** [comment]
Thank you for the report! I totally agree and it is fortunately and easy improvement. I'll make the improvement the next time I am working on DATIS 👍

**Comment by FernandoNotedigo** [comment]
Thanks!

**Comment by rkusa** [comment]
Forgot about this one, but added it today. It will be included in the `3.0.1` release that I'll drop in the next couple of days.
