### ISSUE TITLE
Wind speed wrong?

### ISSUE THREAD

**Issue by burke004** [rkusa/DATIS#88]
Hi! Great project!

I was wondering how you calculate the wind speed. When i calculate the wind speed from a script running in a mission at the position of a carrier i get 22 kts, DATIS reports 9 kts. By looking at the water it's more likely 22 kts than 9 kts.

E: Maybe this an issue to start with.
In station.rs in:
impl Carrier {
    pub fn generate_report(
    ...
    pronounce_number(weather.wind_speed.round(), spoken),

there's no conversion to knots as in impl Airfield, impl WeatherTransmitter, pub fn generate_report.

**Comment by rkusa** [comment]
Fixed and [published](https://github.com/rkusa/DATIS/releases/tag/2.2.2), thanks a lot for the report! You were totally right about the cause, the conversion from m/s to ft was simply missing 👍

**Comment by burke004** [comment]
You're welcome! Keep up the good work!
